<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">    
    
</div>
<div>
    <a style="background: #00A9FF; display: block; width: 40px; height: 16px;" target="_BLANK" href="https://appotapay.com"><img src="https://appotapay.com/images/appota-pay.png" alt="Thanh toán bảo mật với Appota Pay" title="Appota Pay Website" style="border: 1px solid #EEEEEE; width: 40px;" /></a><?php echo $this->getMethod()->getConfigData('message');?>
</div>